// ─────────────────────────────────────────────────────────
// src/models/mongo/sample-data.js — Sample documents
// ─────────────────────────────────────────────────────────

// ═══════════════════════════════════════════════════════════
//  PLAYERS — 10 students
// ═══════════════════════════════════════════════════════════

export const samplePlayers = [
  {
    playerId: "P001",
    pin: "1234",
    name: "أحمد محمد",
    school: "شمس المعارف",
    avatar: "🧑‍🎓",
    stats: { races: 3, bestScore: 322, bestWPM: 35, bestAccuracy: 92, avgScore: 298, totalScore: 894 },
  },
  {
    playerId: "P002",
    pin: "5678",
    name: "سارة علي",
    school: "شمس المعارف",
    avatar: "👩‍🎓",
    stats: { races: 4, bestScore: 403, bestWPM: 42, bestAccuracy: 96, avgScore: 371, totalScore: 1484 },
  },
  {
    playerId: "P003",
    pin: "9012",
    name: "يوسف حسن",
    school: "شمس المعارف",
    avatar: "🧑‍🎓",
    stats: { races: 2, bestScore: 280, bestWPM: 30, bestAccuracy: 88, avgScore: 265, totalScore: 530 },
  },
  {
    playerId: "P004",
    pin: "3456",
    name: "مريم خالد",
    school: "شمس المعارف",
    avatar: "👩‍🎓",
    stats: { races: 5, bestScore: 450, bestWPM: 48, bestAccuracy: 97, avgScore: 412, totalScore: 2060 },
  },
  {
    playerId: "P005",
    pin: "7890",
    name: "عمر سعيد",
    school: "شمس المعارف",
    avatar: "🧑‍🎓",
    stats: { races: 3, bestScore: 310, bestWPM: 33, bestAccuracy: 90, avgScore: 288, totalScore: 864 },
  },
  {
    playerId: "P006",
    pin: "2468",
    name: "نور الدين",
    school: "شمس المعارف",
    avatar: "👩‍🎓",
    stats: { races: 2, bestScore: 260, bestWPM: 28, bestAccuracy: 85, avgScore: 245, totalScore: 490 },
  },
  {
    playerId: "P007",
    pin: "1357",
    name: "ليلى إبراهيم",
    school: "شمس المعارف",
    avatar: "👩‍🎓",
    stats: { races: 4, bestScore: 390, bestWPM: 40, bestAccuracy: 94, avgScore: 360, totalScore: 1440 },
  },
  {
    playerId: "P008",
    pin: "8642",
    name: "كريم وليد",
    school: "شمس المعارف",
    avatar: "🧑‍🎓",
    stats: { races: 3, bestScore: 340, bestWPM: 36, bestAccuracy: 91, avgScore: 315, totalScore: 945 },
  },
  {
    playerId: "P009",
    pin: "9753",
    name: "هند فاروق",
    school: "شمس المعارف",
    avatar: "👩‍🎓",
    stats: { races: 6, bestScore: 480, bestWPM: 52, bestAccuracy: 98, avgScore: 445, totalScore: 2670 },
  },
  {
    playerId: "P010",
    pin: "3141",
    name: "زيدان طارق",
    school: "شمس المعارف",
    avatar: "🧑‍🎓",
    stats: { races: 1, bestScore: 200, bestWPM: 22, bestAccuracy: 82, avgScore: 200, totalScore: 200 },
  },
];

// ═══════════════════════════════════════════════════════════
//  RESULTS — sample race results
// ═══════════════════════════════════════════════════════════

export const sampleResults = [
  // Round 1 — Quarter-final results
  {
    playerId: "P001",
    raceId: "RACE_ROUND_1",   // placeholder — replaced with ObjectId
    round: 1,
    wpm: 35,
    accuracy: 92,
    score: 322,
    time: 45.2,
    correctChars: 180,
    totalKeystrokes: 196,
    textLength: 114,
    textId: 0,
    isFinished: true,
  },
  {
    playerId: "P002",
    raceId: "RACE_ROUND_1",
    round: 1,
    wpm: 42,
    accuracy: 96,
    score: 403,
    time: 38.1,
    correctChars: 190,
    totalKeystrokes: 198,
    textLength: 114,
    textId: 0,
    isFinished: true,
  },
  {
    playerId: "P004",
    raceId: "RACE_ROUND_1",
    round: 1,
    wpm: 48,
    accuracy: 97,
    score: 466,
    time: 34.5,
    correctChars: 195,
    totalKeystrokes: 201,
    textLength: 114,
    textId: 0,
    isFinished: true,
  },
  {
    playerId: "P009",
    raceId: "RACE_ROUND_1",
    round: 1,
    wpm: 52,
    accuracy: 98,
    score: 510,
    time: 31.2,
    correctChars: 198,
    totalKeystrokes: 202,
    textLength: 114,
    textId: 0,
    isFinished: true,
  },

  // Round 2 — Semi-final results
  {
    playerId: "P002",
    raceId: "RACE_ROUND_2",
    round: 2,
    wpm: 44,
    accuracy: 95,
    score: 418,
    time: 36.8,
    correctChars: 188,
    totalKeystrokes: 198,
    textLength: 114,
    textId: 2,
    isFinished: true,
  },
  {
    playerId: "P004",
    raceId: "RACE_ROUND_2",
    round: 2,
    wpm: 50,
    accuracy: 97,
    score: 485,
    time: 33.1,
    correctChars: 196,
    totalKeystrokes: 202,
    textLength: 114,
    textId: 2,
    isFinished: true,
  },
  {
    playerId: "P009",
    raceId: "RACE_ROUND_2",
    round: 2,
    wpm: 54,
    accuracy: 99,
    score: 535,
    time: 29.8,
    correctChars: 200,
    totalKeystrokes: 202,
    textLength: 114,
    textId: 2,
    isFinished: true,
  },

  // Round 3 — Final
  {
    playerId: "P004",
    raceId: "RACE_ROUND_3",
    round: 3,
    wpm: 51,
    accuracy: 98,
    score: 500,
    time: 32.5,
    correctChars: 198,
    totalKeystrokes: 202,
    textLength: 114,
    textId: 5,
    isFinished: true,
  },
  {
    playerId: "P009",
    raceId: "RACE_ROUND_3",
    round: 3,
    wpm: 55,
    accuracy: 99,
    score: 545,
    time: 28.4,
    correctChars: 201,
    totalKeystrokes: 203,
    textLength: 114,
    textId: 5,
    isFinished: true,
  },
];

// ═══════════════════════════════════════════════════════════
//  RACES — 3 rounds of tournament
// ═══════════════════════════════════════════════════════════

const RACE_TEXTS = [
  "العلم نور يُضيء دروب الحياة، ومن ركب موجته وصل إلى شاطئ النجاح. حرصوا على طلب العلم فإنه كنز لا يفنى، ورفيق لا يُضام في كل مكان وزمان.",
  "القراءة هي مفتاح الأفكار الجديدة، وبوابة العقول الواسعة. اقرأوا كل يوم فإن في الكتب حكمة القرون وخبايا الكون.",
  "التربية أسمى رسالة في الوجود، والمعلم بستان يانع يُثمر جيلاً واعياً يحمل هموم وطنه ويسعى لرفعته وتقدمه.",
];

export const sampleRaces = [
  {
    tournamentName: "بطولة شمس المعارف — 2026",
    round: 1,
    roundName: "ربع النهائي",
    maxAdvance: 6,
    status: "finished",
    players: [
      { playerId: "P001", name: "أحمد محمد", school: "شمس المعارف", avatar: "🧑‍🎓", ready: true, progress: 100, finished: true },
      { playerId: "P002", name: "سارة علي", school: "شمس المعارف", avatar: "👩‍🎓", ready: true, progress: 100, finished: true },
      { playerId: "P003", name: "يوسف حسن", school: "شمس المعارف", avatar: "🧑‍🎓", ready: true, progress: 72, finished: false },
      { playerId: "P004", name: "مريم خالد", school: "شمس المعارف", avatar: "👩‍🎓", ready: true, progress: 100, finished: true },
      { playerId: "P005", name: "عمر سعيد", school: "شمس المعارف", avatar: "🧑‍🎓", ready: true, progress: 58, finished: false },
      { playerId: "P006", name: "نور الدين", school: "شمس المعارف", avatar: "👩‍🎓", ready: true, progress: 45, finished: false },
      { playerId: "P007", name: "ليلى إبراهيم", school: "شمس المعارف", avatar: "👩‍🎓", ready: true, progress: 100, finished: true },
      { playerId: "P008", name: "كريم وليد", school: "شمس المعارف", avatar: "🧑‍🎓", ready: true, progress: 88, finished: false },
      { playerId: "P009", name: "هند فاروق", school: "شمس المعارف", avatar: "👩‍🎓", ready: true, progress: 100, finished: true },
      { playerId: "P010", name: "زيدان طارق", school: "شمس المعارف", avatar: "🧑‍🎓", ready: true, progress: 100, finished: true },
    ],
    text: RACE_TEXTS[0],
    textId: 0,
    textLength: RACE_TEXTS[0].length,
    maxDuration: 120,
    startedAt: new Date("2026-03-31T09:00:00Z"),
    finishedAt: new Date("2026-03-31T09:02:15Z"),
    winner: { playerId: "P009", name: "هند فاروق", score: 510, wpm: 52 },
    standings: [
      { rank: 1, playerId: "P009", name: "هند فاروق", school: "شمس المعارف", avatar: "👩‍🎓", score: 510, wpm: 52, accuracy: 98, time: 31.2, finished: true },
      { rank: 2, playerId: "P004", name: "مريم خالد", school: "شمس المعارف", avatar: "👩‍🎓", score: 466, wpm: 48, accuracy: 97, time: 34.5, finished: true },
      { rank: 3, playerId: "P002", name: "سارة علي", school: "شمس المعارف", avatar: "👩‍🎓", score: 403, wpm: 42, accuracy: 96, time: 38.1, finished: true },
      { rank: 4, playerId: "P007", name: "ليلى إبراهيم", school: "شمس المعارف", avatar: "👩‍🎓", score: 380, wpm: 40, accuracy: 94, time: 40.2, finished: true },
      { rank: 5, playerId: "P001", name: "أحمد محمد", school: "شمس المعارف", avatar: "🧑‍🎓", score: 322, wpm: 35, accuracy: 92, time: 45.2, finished: true },
      { rank: 6, playerId: "P010", name: "زيدان طارق", school: "شمس المعارف", avatar: "🧑‍🎓", score: 200, wpm: 22, accuracy: 82, time: 68.0, finished: true },
      { rank: 7, playerId: "P008", name: "كريم وليد", school: "شمس المعارف", avatar: "🧑‍🎓", score: 180, wpm: 20, accuracy: 80, time: 120, finished: false },
      { rank: 8, playerId: "P003", name: "يوسف حسن", school: "شمس المعارف", avatar: "🧑‍🎓", score: 155, wpm: 17, accuracy: 78, time: 120, finished: false },
      { rank: 9, playerId: "P005", name: "عمر سعيد", school: "شمس المعارف", avatar: "🧑‍🎓", score: 120, wpm: 13, accuracy: 75, time: 120, finished: false },
      { rank: 10, playerId: "P006", name: "نور الدين", school: "شمس المعارف", avatar: "👩‍🎓", score: 90, wpm: 10, accuracy: 72, time: 120, finished: false },
    ],
  },
  {
    tournamentName: "بطولة شمس المعارف — 2026",
    round: 2,
    roundName: "نصف النهائي",
    maxAdvance: 3,
    status: "finished",
    players: [
      { playerId: "P001", name: "أحمد محمد", school: "شمس المعارف", avatar: "🧑‍🎓", ready: true, progress: 100, finished: true },
      { playerId: "P002", name: "سارة علي", school: "شمس المعارف", avatar: "👩‍🎓", ready: true, progress: 100, finished: true },
      { playerId: "P004", name: "مريم خالد", school: "شمس المعارف", avatar: "👩‍🎓", ready: true, progress: 100, finished: true },
      { playerId: "P007", name: "ليلى إبراهيم", school: "شمس المعارف", avatar: "👩‍🎓", ready: true, progress: 100, finished: true },
      { playerId: "P009", name: "هند فاروق", school: "شمس المعارف", avatar: "👩‍🎓", ready: true, progress: 100, finished: true },
      { playerId: "P010", name: "زيدان طارق", school: "شمس المعارف", avatar: "🧑‍🎓", ready: true, progress: 65, finished: false },
    ],
    text: RACE_TEXTS[1],
    textId: 2,
    textLength: RACE_TEXTS[1].length,
    maxDuration: 120,
    startedAt: new Date("2026-03-31T09:05:00Z"),
    finishedAt: new Date("2026-03-31T09:06:50Z"),
    winner: { playerId: "P009", name: "هند فاروق", score: 535, wpm: 54 },
    standings: [
      { rank: 1, playerId: "P009", name: "هند فاروق", school: "شمس المعارف", avatar: "👩‍🎓", score: 535, wpm: 54, accuracy: 99, time: 29.8, finished: true },
      { rank: 2, playerId: "P004", name: "مريم خالد", school: "شمس المعارف", avatar: "👩‍🎓", score: 485, wpm: 50, accuracy: 97, time: 33.1, finished: true },
      { rank: 3, playerId: "P002", name: "سارة علي", school: "شمس المعارف", avatar: "👩‍🎓", score: 418, wpm: 44, accuracy: 95, time: 36.8, finished: true },
      { rank: 4, playerId: "P007", name: "ليلى إبراهيم", school: "شمس المعارف", avatar: "👩‍🎓", score: 395, wpm: 42, accuracy: 94, time: 39.0, finished: true },
      { rank: 5, playerId: "P001", name: "أحمد محمد", school: "شمس المعارف", avatar: "🧑‍🎓", score: 340, wpm: 36, accuracy: 92, time: 44.0, finished: true },
      { rank: 6, playerId: "P010", name: "زيدان طارق", school: "شمس المعارف", avatar: "🧑‍🎓", score: 130, wpm: 14, accuracy: 76, time: 120, finished: false },
    ],
  },
  {
    tournamentName: "بطولة شمس المعارف — 2026",
    round: 3,
    roundName: "النهائي",
    maxAdvance: 1,
    status: "finished",
    players: [
      { playerId: "P002", name: "سارة علي", school: "شمس المعارف", avatar: "👩‍🎓", ready: true, progress: 100, finished: true },
      { playerId: "P004", name: "مريم خالد", school: "شمس المعارف", avatar: "👩‍🎓", ready: true, progress: 100, finished: true },
      { playerId: "P009", name: "هند فاروق", school: "شمس المعارف", avatar: "👩‍🎓", ready: true, progress: 100, finished: true },
    ],
    text: RACE_TEXTS[2],
    textId: 5,
    textLength: RACE_TEXTS[2].length,
    maxDuration: 120,
    startedAt: new Date("2026-03-31T09:10:00Z"),
    finishedAt: new Date("2026-03-31T09:11:35Z"),
    winner: { playerId: "P009", name: "هند فاروق", score: 545, wpm: 55 },
    standings: [
      { rank: 1, playerId: "P009", name: "هند فاروق", school: "شمس المعارف", avatar: "👩‍🎓", score: 545, wpm: 55, accuracy: 99, time: 28.4, finished: true },
      { rank: 2, playerId: "P004", name: "مريم خالد", school: "شمس المعارف", avatar: "👩‍🎓", score: 500, wpm: 51, accuracy: 98, time: 32.5, finished: true },
      { rank: 3, playerId: "P002", name: "سارة علي", school: "شمس المعارف", avatar: "👩‍🎓", score: 430, wpm: 45, accuracy: 96, time: 37.0, finished: true },
    ],
  },
];
